/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  MyComponent1 as CompOne
} from './comp1';

declare global {
  interface HTMLCompOneElement extends CompOne, HTMLElement {
  }
  var HTMLCompOneElement: {
    prototype: HTMLCompOneElement;
    new (): HTMLCompOneElement;
  };
  interface HTMLElementTagNameMap {
    "comp-one": HTMLCompOneElement;
  }
  interface ElementTagNameMap {
    "comp-one": HTMLCompOneElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "comp-one": JSXElements.CompOneAttributes;
    }
  }
  namespace JSXElements {
    export interface CompOneAttributes extends HTMLAttributes {
      first?: string;
      last?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
