sudo: false

language: node_js

node_js:
  - '9'

cache:
  directories:
    - node_modules

branches:
  only:
    - master
notifications:
  email: false

before_script:
  - npm prune

script:
  - npm install
  - npm run build:project
  - npm run build

after_success:
  - npm run semantic-release

