sudo: false
language: node_js
cache:
  directories:
    - ~/.npm

node_js:
  - '9'
  - '8'
  - '6'
  - '4'
before_script:
  - npm prune

script:
  - npm install
  - npm run build:project
  - npm run build
after_success:
  - npm run travis-deploy-once "npm run semantic-release"
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
