sudo: false
language: node_js
cache:
  directories:
    - ~/.npm

branches:
      only:
      - master

node_js:
  - '9'

before_install:
  - npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN

before_script:
  - npm prune
  - git checkout master
  - lerna updated --json

script:
  - npm install
  - npm run build:project
  - npm run build
  - lerna publish -m "bump versions [ci skip]" --conventional-commits --yes

after_success:
  - npm run travis-deploy-once "npm run semantic-release"
