sudo: false

language: node_js

node_js:
  - '9'

deploy:
  provider: npm
  email: $NPM_EMAIL
  api_key: $NPM_TOKEN
  on:
    tags: true

cache:
  directories:
    - node_modules

branches:
  only:
    - master
notifications:
  email: false

before_script:
  - npm prune

script:
  - npm install
  - npm run build:project
  - npm run build

after_success:
  - printf "https://registry.npmjs.org/:_authToken=${NPM_TOKEN}" >> ~/.npmrc
  - npm run publish-to-npm

