/**
 * This is an autogenerated file created by the Stencil build process.
 * It contains typing information for all components that exist in this project
 * and imports for stencil collections that might be configured in your stencil.config.js file
 */


import {
  NewsCard as NewsCard
} from './cards/news/src/newscard';

declare global {
  interface HTMLNewsCardElement extends NewsCard, HTMLElement {
  }
  var HTMLNewsCardElement: {
    prototype: HTMLNewsCardElement;
    new (): HTMLNewsCardElement;
  };
  interface HTMLElementTagNameMap {
    "news-card": HTMLNewsCardElement;
  }
  interface ElementTagNameMap {
    "news-card": HTMLNewsCardElement;
  }
  namespace JSX {
    interface IntrinsicElements {
      "news-card": JSXElements.NewsCardAttributes;
    }
  }
  namespace JSXElements {
    export interface NewsCardAttributes extends HTMLAttributes {
      author?: string;
      day?: string;
      month?: string;
      text?: string;
      title?: string;
      year?: string;
    }
  }
}

declare global { namespace JSX { interface StencilJSX {} } }
